### ISSUE TITLE
Potential .{content-hidden} Compatibility Issue with Quarto 1.3.361

### ISSUE THREAD

**Issue by ttalVlatt** [pandoc-ext/section-bibliographies#12]
I updated my Quarto today to version 1.3.361 (the current main version) and all my section bibliographies went blank (i.e., no bibliography was rendered at all). I reverted back to version 1.2.475 that I had been using and they reappeared. Is this something other people have experienced?

**Comment by ttalVlatt** [comment]
I've done some additional fiddling around, and it appears that the issue is specific to if you cite the references in a .{content-hidden} tab, as I have been doing for my Quarto CV. Attached is a repex works with Quarto v1.2 but not with v1.3. I am also going to open this as an issue with Quarto.
[Quarto-Repex.zip](https://github.com/pandoc-ext/section-bibliographies/files/11734901/Quarto-Repex.zip)

**Comment by ttalVlatt** [comment]
In case anyone comes across this, I found out that there was a change in Quarto 1.3 that affected this (see here: https://github.com/quarto-dev/quarto-cli/issues/5904) and was shown a basic workaround. You can create another .lua filter extension that hides the content rather than using .content-hidden. See here for an example: https://github.com/ttalVlatt/ttalVlatt.github.io/tree/main/_extensions/ttalVlatt/hide-me

**Comment by tarleb** [comment]
Thanks for the report and the additional info. I believe that there isn't much we can do in this filter, so I'm closing the issue.
