### ISSUE TITLE
reference section not generated for unnumbered chapters

### ISSUE THREAD

**Issue by mikabr** [pandoc-ext/section-bibliographies#14]
I have an unnumbered chapter (a preface) that should have citations and references just like other chapters, but the filter doesn't appear to generate a reference section for it. (running quarto 1.3.433)

Minimal example:
```
---
format: pdf
bibliography: example.bib
reference-section-title: References
filters:
  - section-bibliographies
citeproc: false
---

# Preface {-}

text citing @frank2012

# Chapter 1

text citing @lewis1973

# Chapter 2

text citing @kraus2019
```
<img width="767" alt="Screen Shot 2023-07-20 at 4 52 34 PM" src="https://github.com/pandoc-ext/section-bibliographies/assets/1414971/7c95dfa2-7400-4b59-9bcf-23c05eb45af4">

Contrast with running pandoc's default citation handling, which does include the unnumbered chapter:
```
---
format: pdf
bibliography: example.bib
reference-section-title: References
citeproc: true
---

# Preface {-}

text citing @frank2012

# Chapter 1

text citing @lewis1973

# Chapter 2

text citing @kraus2019

```
<img width="767" alt="Screen Shot 2023-07-20 at 4 52 12 PM" src="https://github.com/pandoc-ext/section-bibliographies/assets/1414971/6b880174-2169-417a-a14f-f7007acc0aa0">

Seems like this could be due to the filter checking that a section has a number attribute in [line 23](https://github.com/pandoc-ext/section-bibliographies/blob/5b4180c49b3d41974711ed1b74c80548ad42e404/_extensions/section-bibliographies/section-bibliographies.lua#L23)?
```
local function is_section_div (div)
  return div.t == 'Div'
    and div.classes[1] == 'section'
    and div.attributes.number
end
```

**Comment by andrewmcamp** [comment]
I ran into this issue as well. I am not familiar with Lua and so my solution probably isn't best, but I was able to get the code to work by changing the following:

On lines 20-24:
> local function is_section_div (div)
  return div.t == 'Div'
    and div.classes[1] == 'section'
end

On lines 46-52:
>   if bib_header then
    bib_header.identifier = 'bibliography-' .. (header.attributes.number or 999)
    bib_header.level = header.level + 1
  end
  if refs and refs.identifier == 'refs' then
    refs.identifier = 'refs-' .. (header.attributes.number or 999)
  end

As far as I can tell, this hasn't created unanticipated/wanted side effects.

**Comment by mikabr** [comment]
That works great, thanks!

**Comment by tarleb** [comment]
Thanks for the report!
