### ISSUE TITLE
Extension section-bibliographies installed but not found during render

### ISSUE THREAD

**Issue by rolandknapp** [pandoc-ext/section-bibliographies#7]
Environment: RStudio 2022.12.0+353 for Ubuntu Jammy

I am writing a scientific manuscript using Quarto/RStudio. I just installed the section-bibliographies filter as an extension using `quarto install extension pandoc-ext/section-bibliographies` which concluded with "Extension installation complete". I also now see the _extensions/pandoc-ext/section-bibliographies subdirectories in the project directory. I then updated my yaml as described in the section-bibliographies/README. However, when I render the .qmd file, it errors with "Error running filter section-bibliographies: Could not find executable section-bibliographies". I've looked for solutions to this issue, but have come up empty and am hoping you can help. Thanks.

**Comment by tarleb** [comment]
It looks like Quarto tries to run the extension as a JSON filter, which won't work. Not sure what's going wrong there.

Workaround: specify the full path to the filter file. This will force Quarto to use it as a Lua filter:

``` yaml
filters:
  - _extensions/pandoc-ext/section-bibliographies/section-bibliographies.lua
```
